#!/bin/bash
#PBS -q qprod
#PBS -N Flaps2D
#PBS -m ae -M derrien@fzu.cz
#PBS -e Flaps.err
#PBS -o Flaps.log
#PBS -A OPEN-5-22
#PBS -l select=1:ncpus=16:mpiprocs=1:ompthreads=16
#PBS -l walltime=0:15:00

# store submission path
workpath=`pwd`

# load modules for the code
module load intel
module load mkl

# set parameters for calculation 
# export KMP_STACKSIZE=104857600
# export OMP_STACKSIZE=104857600

export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
# export MKL_DYNAMIC="FALSE"
export OMP_DYNAMIC="FALSE"
export OMP_SCHEDULE="DYNAMIC,800"
# ulimit -s unlimited
#KMP_AFFINITY=granularity=fine,compact
export KMP_AFFINITY=granularity=fine,compact,1,0

# let's move to the temporary folder

# change to scratch directory, exit on failure
myjob=`qstat -a -u tderrien | grep 'tderrien' | awk '{ print $1 }' `
TARGETDIR=/scratch/$USER/$myjob
mkdir -p $TARGETDIR
echo "Target:" >> /home/tderrien/LastJobs.log
echo $TARGETDIR >> /home/tderrien/LastJobs.log

cd $TARGETDIR || exit

echo "PBS NODEFILE=" 
cat $PBS_NODEFILE
# cd $PBS_O_WORKDIR || exit

echo "PBS_O_WORKDIR=" 
echo $PBS_O_WORKDIR
echo "" >> /home/tderrien/LastJobs.log 
echo $PBS_O_WORKDIR >> /home/tderrien/LastJobs.log

cp $PBS_O_WORKDIR/Flaps_explicit.out $TARGETDIR
cp $PBS_O_WORKDIR/FermiDatasE.sav $TARGETDIR/FermiDatasE.dat
cp $PBS_O_WORKDIR/FermiDatasH.sav $TARGETDIR/FermiDatasH.dat

echo "Where am I ?"
pwd

echo "What have I got ?"
ls

echo "Executing code..."
./Flaps_explicit.out
exit

# echo "Copying files to ..."
# echo $workpath

# cp *.dat -f $workpath
# cp *.log -f $workpath
# cp *.err -f $workpath
